In [4]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

C:\Users\amit\Anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d

In [5]:
from subprocess import check_output
from datetime import time
#print(check_output(["ls","C:\Users\amit\Desktop\practice\gym.csv"]).decode("utf8"))

In [6]:
def time_to_seconds(time):
    return time.hour*3600+ time.minute *60 + time.second

In [8]:
df = pd.read_csv(r"C:\Users\amit\Desktop\practice\gym.csv")
# Drop columns
df = df.drop("date", axis=1)
# center timestamp
noon = time_to_seconds(time(12, 0, 0))
df.timestamp = df.timestamp.apply(lambda t: abs(noon - t))
columns = ["day_of_week", "month", "hour"]
df = pd.get_dummies(df, columns=columns)
df.head(10)

,number_people,timestamp,is_weekend,is_holiday,temperature,is_start_of_semester,is_during_semester,day_of_week_0,day_of_week_1,day_of_week_2,...,hour_14,hour_15,hour_16,hour_17,hour_18,hour_19,hour_20,hour_21,hour_22,hour_23
0,37,18011,0,0,71.76,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
1,45,19214,0,0,71.76,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
2,40,19815,0,0,71.76,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
3,44,20416,0,0,71.76,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
4,45,21017,0,0,71.76,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
5,46,21618,0,0,72.15,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
6,43,22808,0,0,72.15,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
7,53,23409,0,0,72.15,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
8,54,24014,0,0,72.15,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
9,43,24615,0,0,72.15,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0

In [10]:
#extract trainning and testing data value we used will get data into data frame [X,y]
data=df.values
X=data[:,1:]
y=data[:,0]
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=42)

In [13]:
#now we scale the feature between the -1 to 1
scaler=StandardScaler()
scaler.fit(X_train)
X_train=scaler.transform(X_train)
X_test=scaler.transform(X_test)

In [14]:
#create a model npw
model =RandomForestRegressor()

In [ ]:
#now we take n_estimator it usually tell how many decision tree that we will used 
estimators=np.arange(10,200,10)
score=[]
for n in estimators:
    model.set_params(n_estimators=n)
    model.fit(X_train,y_train)
    score.append(model.score(X_test,y_test))
plt.label("effect of n estimators ")
plt.xlabel="n_estimators"
plt.ylabel="scores"
plt.plot(estimators ,score )